"""auto add comment

Revision ID: 2e011e32c9eb
Revises: ecddacaf168d
Create Date: 2023-05-16 11:27:33.702337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e011e32c9eb'
down_revision = 'ecddacaf168d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_alch', sa.Column('comment', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_alch', 'comment')
    # ### end Alembic commands ###
